#!/usr/bin/env python3

wheat_fa = 'AGCAC----CCTCCCACCTCATCCCACCCTTCTGATCTCAATCCAACG-TCG-----------CATCTCCACCGTCTCGC-GGATCGACCCAG----CGAAGTCCCTC--CCGCC--CCCAAAGTCCC--------CCAAATCTTGCAGT-TCCCTCCTAAATCCTCCCCA----TATAAACC-------AA---CCCCC-CGCCCTCAGATCCCTAATCCCA--------TCGCAAGC-ATCAGACTCCCTC---C-AAAGCAG---GCA--------------GCAGCTCCTC-TTCTTCCTAATCACACTATCTCGGAGAG-------------------------GAGCGGCCATGTCTGGGCGCGACAAGGGCGGCAAGGGGCTGGGCAAGGGCGGCGCCAAGCGGCACCGGAAGGTCCTCCGCGACAACATCCAGGGCATCACCAAGCCGGCGATCCGGAGGCTGGCCAGGAGGGGCGGCGTGAAGCGCATCTCCGGCCTCATCTACGAGGAGACCCGCGGCGTCCTCAAGATCTTCCTCGAGAACGTCATCCGCGACGCCGTCACCTACACCGAGCACGCCCGCCGCAAAACCGTCACCGCCATGGACGTCGTCTACGCGCTCAAGCGCCAGGGCCGCACCCTCTACGGCTTCGGAGGCTAGA---TTTGT--------GTGGTGAAGCAA----CTTCCTCGT---TTGCTCTGTGATCTGTGC---TGTCGTAGATGAGATTTAC-TGATTT--------------GGCGTGCGCCGGTTGTATTCTGTCATGGGGTTCA-----GTGGGCTGTGTAATACCTTGCTCTGTACTTCTGTTCAATGCAATCACTT-CTATTCTGAA'
human_fa = 'TCTAGAGATGGCGCCATTTGATTCCAGCAGCCACAAAGCACTAGAACAATCGATGCTAAGAGGTGACAGGAAAAACAGGCTGCAAAGACCCAGACAATGGAATGCAGCGGTGGTCAGCCTAAAACACTGTAGAAGGGCAAGATGAGCTGAGTAATTTTTAACTGGGCATCATTTTTAGAAACTGGAGTTTAAGTACCCCCTTTTCCATTTTTTCCTGAAGTCGTGGGCAGGGCGCAAGGTCTGTGAATCGGCCGACCGGATGCAGCTGGTGTGGAGAGTTCCCAATCAGGTCCGATTTATTACTATATAAAGTACTGCTGCGAGGCTTGCCGTGTTGCATTTTGTTTAGTACAAGACATGTCTGGGCGCGGCAAAGGCGGGAAGGGTCTGGGCAAAGGAGGCGCTAAGCGCCACCGCAAAGTTCTGCGCGACAACATTCAGGGCATCACCAAGCCCGCCATCCGACGCCTGGCACGGCGTGGAGGCGTTAAGCGCATCTCAGGCCTTATATACGAGGAGACACGCGGAGTTCTTAAAGTGTTTTTGGAGAATGTAATCCGCGATGCAGTTACCTACACGGAGCACGCCAAACGCAAGACAGTCACAGCCATGGACGTGGTTTACGCGCTCAAGCGCCAGGGCCGCACCCTGTATGGCTTTGGCGGCTGAGTGTTTTACTTACTTACACGGTTCCTCAAAGGCCCTTCTCAGGGCCACCCATGAAGTCTGTGAAAGAGCTGTAGACTAAAGATAGTTAATTTCTTAAGAACACTTAAACGTATGGCAGTTTTGGCAAATTAGCGATTCCACATAAGCAGTCGCTGAAGTTTGAGGTTCGGTGCCCCT-TTCA--GC-ATTACTTAGTGGTTAAAA'

same_count = 0
for pos in range(len(wheat_fa)):
	if wheat_fa[pos] == human_fa[pos]:
		same_count += 1
per_id = same_count/len(wheat_fa)

print(per_id)



